# **Pandas Basics on CSV reading and Data Manipulation**

Pandas is defined as an open-source library that provides high-performance data manipulation in Python. It is built on top of the NumPy package, which means Numpy is required for operating the Pandas. Pandas is a popular library for working with tabular data, as it provides some sets of powerful tools like DataFrame and Series that mainly used for analyzing the data. Besides, Pandas also has higher performance when dealing with very large dataset. In this exercise, we will see how can we use Pandas to read csv file and do some basic calculation.

In this exercise we have three different csv file, which are data coming from the classification results and validation data in the Landsat scene.

### Data overview:
**1_accuracy_groundtruth.csv** 
Validation data manually collected
* it has one column with three values, 1: snow, 2: snowfree, 12: invalid

**2_accuracy_class1.csv** 
Classification results using classification scheme 1
* it has one column with three values, 11: snow, 10: snowfree, 12: cloud, 15: water, 16: shadow, 0: missing data

**3_accuracy_class2.csv** 
Classification results using classification scheme 2
* it has one column with three values, 11: snow, 10: snowfree, 12: cloud, 15: water, 16: shadow, 0: missing data

### **Note: All cloud, water, shadow, and missing data are considered invalid in the ground truth data.**

## Task 1: Import required libraries

In [1]:
# import libraries
import numpy as np
import pandas as pd

## Task 2: Data read
Read all 3 csv files into Pandas dataframe

* Ground Truth as **groundtruth_df**
* Classification 1 as **class1_df**
* Classification 2 as **class2_df**

In [2]:
groundtruth_path = '1_accuracy_groundtruth.csv'
groundtruth_df = pd.read_csv(groundtruth_path)
groundtruth_df

snowcover
0              1
1              1
2              1
3              1
4              1
...          ...
15821         12
15822         12
15823         12
15824         12
15825         12

[15826 rows x 1 columns]

In [3]:
class1_path = '2_classification_method_1.csv'
class1_df = pd.read_csv(class1_path)
class1_df

LE07_L1TP_
0            11.0
1            11.0
2            11.0
3            11.0
4            12.0
...           ...
15821        10.0
15822        10.0
15823        10.0
15824        10.0
15825        10.0

[15826 rows x 1 columns]

In [4]:
class2_path = r'3_classification_method_2.csv'
class2_df = pd.read_csv(class2_path)
class2_df

newclass_2
0            11.0
1            11.0
2            11.0
3            11.0
4            11.0
...           ...
15821        15.0
15822        15.0
15823        15.0
15824        15.0
15825        15.0

[15826 rows x 1 columns]

## Task 3: Data overview
Print the first 10 lines of **groundtruth_df** and the last line of **groundtruth_df**

In [5]:
groundtruth_df.head(10)

snowcover
0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1

In [6]:
groundtruth_df.tail(1)

snowcover
15825         12

## Task 4: Funtion for dataframe length
Write a function **check_len()** to test if the number of rows in the three Dataframes are the same. It takes input of **df1**, **df2**, **df3**. 
<br>If they are the same, return **True**. If not, return **False**. <br>Apply the three dataframes into the function.

In [7]:
def check_len(df1,df2,df3):
  len1 = len(groundtruth_df)
  len2 = len(class1_df)
  len3 = len(class2_df)
  if len1 == len2 == len3:
    return True
  else:
    return False

In [8]:
check_len(groundtruth_df,class1_df,class2_df)

True

## Task 5: New pandas dataframe
Create a Pandas Dataframe which includes three columns: 
* **truth**: from groundtruth_df
* **class1**: from class1_df
* **class2**: from class2_df


In [9]:
data = {'truth': np.array(groundtruth_df.iloc[:, 0]),'class1': np.array(class1_df.iloc[:, 0]), 'class2': np.array(class2_df.iloc[:, 0])}
df = pd.DataFrame(data=data)

In [10]:
df

truth  class1  class2
0          1    11.0    11.0
1          1    11.0    11.0
2          1    11.0    11.0
3          1    11.0    11.0
4          1    12.0    11.0
...      ...     ...     ...
15821     12    10.0    15.0
15822     12    10.0    15.0
15823     12    10.0    15.0
15824     12    10.0    15.0
15825     12    10.0    15.0

[15826 rows x 3 columns]

## Task 6: Data Post-processing
Now we shall have a Pandas dataframe with 3 columns of different values representing different classes. But right now invalid class have different values in class1 and class2 compared to the truth column. And the data type of three columns are not identical. So we need to:

1) Make sure all columns have the same data type (integer)
2) Change **cloud, water, shadow, and missing data** in class1 and class2 to **invalid class (12)**
3) In the column **truth** change values 1 into 11, 0 into 10 

So at the end, we should have:
* **10: Snowfree**
* **11: Snow**
* **12: Invalid (Snow, Cloud, Missing data, Shadow)**

In [11]:
print(df.truth.unique())
print(df.class1.unique())
print(df.class2.unique())

[ 1  0 12]
[11. 12. 10.  0. 15.]
[11. 16. 12. 10. 15.]


In [12]:
df.truth.replace(0,10, inplace=True)
df.truth.replace(1,11, inplace=True)
df.replace(15,12, inplace=True)
df.replace(16,12, inplace=True)
df.replace(0,12, inplace=True)

In [13]:
df = df.astype('Int64')

In [14]:
print(df.truth.unique())
print(df.class1.unique())
print(df.class2.unique())

<IntegerArray>
[11, 10, 12]
Length: 3, dtype: Int64
<IntegerArray>
[11, 12, 10]
Length: 3, dtype: Int64
<IntegerArray>
[11, 12, 10]
Length: 3, dtype: Int64


## Task 7: Handling Missing Values
We have to pay attention that for some columns values might not be available in class1 or class2. To deal with those columns, it is the best to remove the whole row, even through only vlaues in one single column is missing.

In [15]:
df.dropna(axis=0, how='any', inplace=True)

And we need to look at the first five lines of df again.

In [16]:
df.head()

truth  class1  class2
0     11      11      11
1     11      11      11
2     11      11      11
3     11      11      11
4     11      12      11

## Task 8: Data Exploration

Find out how many observations remain for each class in the truth column (three classes in total).

In [17]:
df.groupby('truth').count()

class1  class2
truth                
10       5092    5092
11       5205    5205
12       5529    5529

## Task 9: Data Export

Export df as a csv file.

In [59]:
df.to_csv(r'task9_solution.csv', index=False)